spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_escolar_new?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${dbUser:admin}
    password: ${dbPass:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect